name: 'Build APK'


inputs:
  matrix-target:
    description: 'The build target to use'
    required: true
    default: 'apk --split-per-abi'

runs:
  using: 'docker'
  image: 'Dockerfile'

outputs:
  built-apk:
    description: 'The path to the built APK'


permissions:
  contents: 'read'


steps:
  - name: 'Set up JDK 11'
    uses: 'actions/setup-java@v4'
    with:
      java-version: '11'
      distribution: 'temurin'

  - name: 'Clone Flutter repository with master channel'
    uses: 'subosito/flutter-action@v1'
    with:
      channel: 'master'

  - name: 'Check Flutter environment'
    run: 'flutter doctor -v'

  - name: 'Checkout code'
    uses: 'actions/checkout@v3'

  - name: 'Get packages'
    run: 'flutter pub get'

  - name: 'Build APK'
    id: 'build'
    run: 'flutter build ${{ inputs.matrix-target }} && echo "::set-output name=built-apk::build/app/outputs/flutter-apk/"'


  - name: 'Upload APK'
    uses: 'actions/upload-artifact@v2'
    with:
      name: 'Built APK'
      path: '${{ steps.build.outputs.built-apk }}'