name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    strategy:
      matrix:
        abi: [arm64-v8a, armeabi-v7a, x86, x86_64]
        include:
          - abi: arm64-v8a
            buildType: release
          - abi: armeabi-v7a
            buildType: release
          - abi: x86
            buildType: release
          - abi: x86_64
            buildType: release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 30
        ndk-version: 21.4.7075529
        build-tools: 30.0.3

    - name: Install dependencies
      run: yes | sdkmanager --licenses && sdkmanager "platforms;android-30" "build-tools;30.0.3"

    - name: Build APK
      run: ./gradlew assemble${{ matrix.buildType }} -PbuildAbi=${{ matrix.abi }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-${{ matrix.buildType }}-${{ matrix.abi }}.apk
        path: app/build/outputs/apk/${{ matrix.buildType }}/app-${{ matrix.buildType }}-${{ matrix.abi }}.apk
